"""Typing protocol for the lab surface used by ``lab_primitives`` dispatch (fakes in tests)."""
from __future__ import annotations

from typing import Any, Dict, Protocol, runtime_checkable


@runtime_checkable
class LabPrimitiveSurface(Protocol):
    """Methods invoked by ``dispatch`` (atomic steps + read helpers)."""

    def get_lab_state(self) -> Dict[str, Any]: ...

    def return_tunables_for_tag(self, tag_id: str) -> Dict[str, Any]: ...

    def return_measurables_for_tag(self, tag_id: str) -> Dict[str, Any]: ...

    async def record_measurables_for_tag(self, tag_id: str) -> Dict[str, Any]: ...

    async def move_component(self, target_id: str, target_pose: Dict[str, float]) -> None: ...

    async def move_motor(self, target_id: str, motor_id: int, distance: float) -> None: ...

    async def motor_set_zero(self, target_id: str, motor_id: int) -> None: ...

    async def optimize_component(self, target_id: str, strategy: str, params: Dict[str, Any]) -> None: ...

    async def remove_component(self, target_id: str) -> None: ...

    async def store_component(self, target_id: str) -> None: ...

    async def place_from_storage(self, target_id: str, target_pose: Dict[str, Any]) -> None: ...

    async def affirm_placed_at_current(self, target_id: str) -> None: ...

    async def repack_storage_slot(self, target_id: str) -> None: ...

    async def recenter_stored_in_inventory(self, target_id: str) -> None: ...
