/** Mutable application state (single source for lab UI). */
export const store = {
    labState: null,
    ghostState: {},
    draggingComponent: null,
    isDragging: false,
    dragOffset: { x: 0, y: 0 },
    pendingCommands: new Set(),
    selectedComponent: null,
    availableStrategies: null,
    availableRecipes: [],
    laserLineCoeffs: null,
    previousSystemStatus: 'IDLE',
    forceGhostSync: false,
    isOptimizing: false,
    isOptimizingFeedActive: false,
    optimizationData: [],
    isRecording: false,
    currentRecipeSteps: [],
    catalogMap: {},
    catalogCache: null,
    selectedTableCam: 1,
    /** Seconds; used for GET /api/table-cam/capture exposure query param */
    tableCamExposure: 0.2,
    tableCamLastBlobUrl: null,
};
