"""Catalog loading, validation, and capability inference."""

from .bundle import (
    active_catalog_v1_document,
    filter_v1_catalog_to_active_tags,
    merged_catalog_maps,
    merged_catalog_rows,
)
from .schema import (
    CatalogValidationError,
    HardwareBinding,
    catalog_declared_primitives,
    catalog_is_fixed_instrument,
    catalog_is_optimize_placeable,
    catalog_is_placeable_on_table,
    catalog_has_motors,
    catalog_optimize_strategies,
    enrich_catalog_row_optimize,
    find_tag_id_for_cam_id,
    infer_default_capabilities,
    live_feed_channel,
    load_component_library_rows,
    normalize_capabilities,
    resolve_hardware_binding,
    resolve_cam_id_for_tag,
    resolve_telemetry_stream_backend,
    teleop_channel,
    telemetry_channel,
    validate_catalog_v1,
)

__all__ = [
    "CatalogValidationError",
    "HardwareBinding",
    "catalog_declared_primitives",
    "catalog_is_fixed_instrument",
    "catalog_is_optimize_placeable",
    "catalog_is_placeable_on_table",
    "catalog_has_motors",
    "catalog_optimize_strategies",
    "enrich_catalog_row_optimize",
    "infer_default_capabilities",
    "live_feed_channel",
    "normalize_capabilities",
    "teleop_channel",
    "load_component_library_rows",
    "validate_catalog_v1",
    "active_catalog_v1_document",
    "filter_v1_catalog_to_active_tags",
    "merged_catalog_maps",
    "merged_catalog_rows",
    "find_tag_id_for_cam_id",
    "resolve_hardware_binding",
    "resolve_cam_id_for_tag",
    "resolve_telemetry_stream_backend",
    "telemetry_channel",
]
