"""Register custom lab backends (digital twins, bench simulators, …).

``scripts/create_lab_communicator.py`` appends ``register_communicator(...)`` calls
here. Do not edit ``shared/communicator_factory.py`` by hand for new backends.
"""

from __future__ import annotations

# Example (generated by create_lab_communicator.py):
# from lab_communicator.my_backend import MyBackendLabCommunicator
# from lab_communicator.shared.communicator_factory import register_communicator
# register_communicator("my_backend", MyBackendLabCommunicator)
