#!/usr/bin/env python3
"""Scaffold a new lab_communicator backend package + optional lab_view bundle.

Usage (from repository root):

  python scripts/ops/create_lab_communicator.py my_backend
  python scripts/ops/create_lab_communicator.py my_backend --with-lab-view
  python scripts/ops/create_lab_communicator.py my_backend --with-lab-view --lab-view-root backend/lab_communicator/my_backend/lab_view

See backend/lab_communicator/README.md for architecture and wiring into main.py.

Rules:
  - Package name must be ``snake_case`` (letters, digits, underscore; cannot start with a digit).
  - Names ``mock``, ``real``, ``shared``, ``tests`` are reserved.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from datetime import datetime
from pathlib import Path


_RESERVED = frozenset({"mock", "real", "shared", "tests"})
_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _snake_to_class(name: str) -> str:
    parts = [p for p in name.split("_") if p]
    return "".join(p[:1].upper() + p[1:] for p in parts)


def _minimal_lab_state() -> dict:
    return {
        "system_status": "IDLE",
        "last_updated": datetime.now().isoformat(),
        "components": {},
        "optimization_step": 0,
        "optimization_run_dir": None,
        "holding": {
            "tag_id": None,
            "nominal_pose": None,
            "requires_operator_confirm": False,
        },
    }


def _write_init(pkg: Path, module: str, class_name: str) -> None:
    text = f'''"""Placeholder lab communicator backend (scaffold).

Import::

    from lab_communicator.{module} import {class_name}

Generated by ``scripts/ops/create_lab_communicator.py`` — replace stub primitives
with real hardware or simulation logic.
"""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from lab_communicator.{module}.communicator import {class_name}

__all__ = ["{class_name}"]


def __getattr__(name: str):
    if name == "{class_name}":
        from lab_communicator.{module}.communicator import {class_name}
        return {class_name}
    raise AttributeError(f"module 'lab_communicator.{module}' has no attribute {{name!r}}")
'''
    (pkg / "__init__.py").write_text(text, encoding="utf-8")


def _write_communicator(pkg: Path, module: str, class_name: str) -> None:
    text = f'''"""{class_name} — checklist-shaped placeholder (see lab_communicator/README.md)."""

from __future__ import annotations

import json
import os
from typing import Any, Callable, Dict, Optional

from lab_communicator.base import LabCommunicator
from lab_model.catalog.bundle import merged_catalog_maps
from lab_communicator.shared.lab_view_config import get_lab_view_paths
from lab_model.state.snapshot import LabPose


class {class_name}(LabCommunicator):
    """Memory-resident lab backend with stub primitives (asyncio sleep / no-op returns).

    Replace :mod:`lab_communicator.{module}.primitives` with real hardware steps.
    """

    log_prefix = "[{module.upper()} LAB]"

    def __init__(self) -> None:
        super().__init__()
        paths = get_lab_view_paths()
        print(f"{{self.log_prefix}} LAB_VIEW_PATH={{paths.root_dir}}")

        rows, cmap = merged_catalog_maps()
        self.catalog = rows
        self.catalog_map = cmap

        if os.path.isfile(paths.lab_state_json):
            with open(paths.lab_state_json, "r", encoding="utf-8") as f:
                self.current_state = json.load(f)
        # else: keep seeded defaults from :meth:`LabCommunicator.__init__`

    def _persist_state(self) -> None:
        pass

    def refresh_state(self) -> None:
        self.refresh_pose_from_camera()

    def get_video_stream(self, fps: int = 10):  # noqa: ARG002
        while True:
            yield b""
            break

    # --- Primitive hooks (1-line delegations) ---

    async def _primitive_move_motor(self, target_id: str, motor_id: int, distance: float) -> None:
        from lab_communicator.{module}.primitives import primitive_move_motor
        await primitive_move_motor(self, target_id, motor_id, distance)

    async def _primitive_move_component(self, target_id: str, commanded: LabPose):
        from lab_communicator.{module}.primitives import primitive_move_component
        return await primitive_move_component(self, target_id, commanded)

    async def _primitive_pick_component(
        self, target_id: str, commanded: LabPose, params: Dict[str, Any]
    ) -> float:
        from lab_communicator.{module}.primitives import primitive_pick_component
        return await primitive_pick_component(self, target_id, commanded, params)

    async def _primitive_hover_component(
        self, target_id: str, commanded: LabPose, speed: int
    ) -> Optional[LabPose]:
        from lab_communicator.{module}.primitives import primitive_hover_component
        return await primitive_hover_component(self, target_id, commanded, speed)

    async def _primitive_place_from_hover(
        self, target_id: str, commanded: LabPose, params: Dict[str, Any]
    ) -> None:
        from lab_communicator.{module}.primitives import primitive_place_from_hover
        await primitive_place_from_hover(self, target_id, commanded, params)

    async def _primitive_scan_rotate_in_place(
        self,
        *,
        target_id: str,
        mode: str,
        theta_min: float,
        theta_max: float,
        speed: float,
        axis: str,
        base_x: float,
        base_y: float,
        base_z: Optional[float],
        params: Dict[str, Any],
        on_rotation_update: Callable[[float], None],
    ) -> None:
        from lab_communicator.{module}.primitives import primitive_scan_rotate_in_place
        await primitive_scan_rotate_in_place(
            self,
            target_id=target_id,
            mode=mode,
            theta_min=theta_min,
            theta_max=theta_max,
            speed=speed,
            axis=axis,
            base_x=base_x,
            base_y=base_y,
            base_z=base_z,
            params=params,
            on_rotation_update=on_rotation_update,
        )

    async def _primitive_record_measurables(self, tag_id: str, catalog_meta: Dict[str, Any]):
        from lab_communicator.{module}.primitives import primitive_record_measurables
        return await primitive_record_measurables(self, tag_id, catalog_meta)

    async def _primitive_optimize_component(
        self,
        *,
        target_id: str,
        strategy_name: str,
        params: Dict[str, Any],
        progress_callback: Callable[..., None],
    ):
        from lab_communicator.{module}.primitives import primitive_optimize_component
        return await primitive_optimize_component(
            self,
            target_id=target_id,
            strategy_name=strategy_name,
            params=params,
            progress_callback=progress_callback,
        )

    async def _primitive_add_component_to_state(
        self, component_data: Dict[str, Any], existing_components: Dict[str, Any]
    ):
        from lab_communicator.{module}.primitives import primitive_add_component_to_state
        return await primitive_add_component_to_state(self, component_data, existing_components)
'''
    (pkg / "communicator.py").write_text(text, encoding="utf-8")


def _write_primitives(pkg: Path, module: str, class_name: str) -> None:
    text = f'''"""Stub primitive implementations for :class:`~lab_communicator.{module}.communicator.{class_name}`.

Replace sleeps with real hardware / simulation. Do not read or write
``communicator.current_state`` here — the base orchestrator owns state
(see ``lab_model.platform`` integrity checks and ``lab_communicator/README.md``).
"""

from __future__ import annotations

import asyncio
import random
from typing import TYPE_CHECKING, Any, Callable, Dict, Optional

from lab_model.domain.component import PRESENCE_BREADBOARD, new_component_entry
from lab_model.domain.holding import DEFAULT_HOVER_Z_MM

from lab_model.state.snapshot import LabPose

if TYPE_CHECKING:
    from lab_communicator.{module}.communicator import {class_name}


async def primitive_move_motor(
    communicator: "{class_name}",  # noqa: ARG001
    target_id: str,  # noqa: ARG001
    motor_id: int,  # noqa: ARG001
    distance: float,  # noqa: ARG001
) -> None:
    await asyncio.sleep(0.05)


async def primitive_pick_component(
    communicator: "{class_name}",  # noqa: ARG001
    target_id: str,  # noqa: ARG001
    commanded: LabPose,  # noqa: ARG001
    params: Dict[str, Any],  # noqa: ARG001
) -> float:
    await asyncio.sleep(0.05)
    return float(DEFAULT_HOVER_Z_MM)


async def primitive_hover_component(
    communicator: "{class_name}",  # noqa: ARG001
    target_id: str,  # noqa: ARG001
    commanded: LabPose,
    speed: int,  # noqa: ARG001
) -> Optional[LabPose]:
    await asyncio.sleep(0.05)
    return LabPose(
        x=commanded.x + random.uniform(-0.03, 0.03),
        y=commanded.y + random.uniform(-0.03, 0.03),
        z=commanded.z,
        rotation=commanded.rotation,
    )


async def primitive_place_from_hover(
    communicator: "{class_name}",  # noqa: ARG001
    target_id: str,  # noqa: ARG001
    commanded: LabPose,  # noqa: ARG001
    params: Dict[str, Any],  # noqa: ARG001
) -> None:
    await asyncio.sleep(0.05)


async def primitive_scan_rotate_in_place(
    communicator: "{class_name}",  # noqa: ARG001
    *,
    target_id: str,  # noqa: ARG001
    mode: str,  # noqa: ARG001
    theta_min: float,
    theta_max: float,
    speed: float,
    axis: str,  # noqa: ARG001
    base_x: float,  # noqa: ARG001
    base_y: float,  # noqa: ARG001
    base_z: Optional[float],  # noqa: ARG001
    params: Dict[str, Any],  # noqa: ARG001
    on_rotation_update: Callable[[float], None],
) -> None:
    steps = max(1, min(12, int(abs(theta_max - theta_min) / max(speed, 1e-6)) + 1))
    for i in range(1, steps):
        frac = i / steps
        cur_rot = theta_min + (theta_max - theta_min) * frac
        on_rotation_update(cur_rot)
        await asyncio.sleep(0.03)


async def primitive_move_component(
    communicator: "{class_name}",  # noqa: ARG001
    target_id: str,  # noqa: ARG001
    commanded: LabPose,
) -> Optional[LabPose]:
    await asyncio.sleep(0.05)
    return LabPose(
        x=commanded.x + random.uniform(-0.05, 0.05),
        y=commanded.y + random.uniform(-0.05, 0.05),
        z=commanded.z,
        rotation=commanded.rotation,
    )


async def primitive_record_measurables(
    communicator: "{class_name}",  # noqa: ARG001
    tag_id: str,  # noqa: ARG001
    catalog_meta: Dict[str, Any],  # noqa: ARG001
):
    await asyncio.sleep(0.02)
    return None


async def primitive_optimize_component(
    communicator: "{class_name}",
    *,
    target_id: str,
    strategy_name: str,  # noqa: ARG001
    params: Dict[str, Any],  # noqa: ARG001
    progress_callback: Callable[..., None],
):
    cur = (communicator.return_measurables_for_tag(target_id) or {{}}).get("pose") or {{}}
    base_x = float(cur.get("x", 0.0))
    base_y = float(cur.get("y", 0.0))
    base_rot = float(cur.get("rotation", 0.0))
    for k in range(1, 4):
        await asyncio.sleep(0.05)
        progress_callback(step=k)
    return {{
        "score": 0.5,
        "final_pose": {{"x": base_x, "y": base_y, "rotation": base_rot}},
    }}


async def primitive_add_component_to_state(
    communicator: "{class_name}",  # noqa: ARG001
    component_data: Dict[str, Any],
    existing_components: Dict[str, Any],  # noqa: ARG001
):
    tag_id = component_data.get("tag_id")
    comp_type = component_data.get("type", "OPTICAL_MIRROR")
    await asyncio.sleep(0.02)
    return new_component_entry(
        tag_id,
        comp_type,
        presence=PRESENCE_BREADBOARD,
        nominal_pose={{"x": 0.0, "y": 0.0, "rotation": 0.0}},
        meas_pose={{"x": 0.0, "y": 0.0, "rotation": 0.0}},
        placement_mode="MANUAL",
        in_storage=False,
        slot=None,
    )


__all__ = [
    "primitive_move_motor",
    "primitive_pick_component",
    "primitive_hover_component",
    "primitive_place_from_hover",
    "primitive_scan_rotate_in_place",
    "primitive_move_component",
    "primitive_record_measurables",
    "primitive_optimize_component",
    "primitive_add_component_to_state",
]
'''
    (pkg / "primitives.py").write_text(text, encoding="utf-8")


def _copy_lab_view(template: Path, dest: Path, *, communicator_id: str) -> None:
    if dest.exists():
        raise SystemExit(f"lab_view destination already exists: {dest}")
    shutil.copytree(template, dest)
    lab_state_path = dest / "lab_state.json"
    if not lab_state_path.is_file():
        with open(lab_state_path, "w", encoding="utf-8") as f:
            json.dump(_minimal_lab_state(), f, indent=2)
            f.write("\n")
    manifest_path = dest / "lab_manifest.json"
    manifest: dict = {
        "version": 1,
        "description": "Deployment identity for this lab view bundle.",
        "communicator": communicator_id,
        "session_checkpoint": True,
    }
    if communicator_id == "real":
        manifest["lab_automation_path"] = "../lab_automation"
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")


def main() -> int:
    parser = argparse.ArgumentParser(description="Create a lab_communicator backend scaffold.")
    parser.add_argument(
        "name",
        help="Python package name (snake_case), e.g. bench_sim → BenchSimLabCommunicator",
    )
    parser.add_argument(
        "--with-lab-view",
        action="store_true",
        help="Copy lab_view starter files from real/lab_view/default into --lab-view-root.",
    )
    parser.add_argument(
        "--lab-view-root",
        type=str,
        default="",
        help="Destination directory for the bundle (default: backend/lab_communicator/<name>/lab_view).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Allow overwriting an existing communicator package directory.",
    )
    args = parser.parse_args()

    name = args.name.strip().lower().replace("-", "_")
    if not _NAME_RE.match(name):
        print("Invalid name: use snake_case [a-z][a-z0-9_]*", file=sys.stderr)
        return 2
    if name in _RESERVED:
        print(f"Reserved package name: {name}", file=sys.stderr)
        return 2

    root = _repo_root()
    lc_root = root / "backend" / "lab_communicator"
    pkg = lc_root / name
    if pkg.exists() and not args.force:
        print(f"Already exists (use --force): {pkg}", file=sys.stderr)
        return 2

    class_name = _snake_to_class(name) + "LabCommunicator"

    if pkg.exists():
        shutil.rmtree(pkg)
    pkg.mkdir(parents=True)

    _write_init(pkg, name, class_name)
    _write_communicator(pkg, name, class_name)
    _write_primitives(pkg, name, class_name)

    lv_template = lc_root / "real" / "lab_view" / "default"
    if not lv_template.is_dir():
        print(f"Missing template lab_view: {lv_template}", file=sys.stderr)
        return 2

    lab_view_dest: Path | None = None
    if args.with_lab_view:
        lab_view_dest = Path(args.lab_view_root) if args.lab_view_root else pkg / "lab_view"
        if not lab_view_dest.is_absolute():
            lab_view_dest = root / lab_view_dest
        _copy_lab_view(lv_template, lab_view_dest, communicator_id=name)

    print(f"Created package: backend/lab_communicator/{name}/")
    print(f"  Class: {class_name}")
    if lab_view_dest is not None:
        print(f"  lab_view: {lab_view_dest.relative_to(root)}")
        print()
        print("Next: set in .env (repo root):")
        print(f"  LAB_VIEW_PATH={lab_view_dest.relative_to(root).as_posix()}")
        print(f"  (lab_manifest.json in that bundle sets communicator={name!r})")
    else:
        print()
        print("No lab_view copied. Point LAB_VIEW_PATH at any bundle that contains:")
        print("  lab_manifest.json, layout.json, laser_lines.json, component_library.json,")
        print("  active_catalog.json, motor_rotations.json (+ lab_state.json recommended).")
    print()
    print(
        "Register your class in lab_communicator/shared/communicator_factory.py "
        f"(add {name!r} to create_communicator)."
    )
    print("CI guardrails: lab_model.platform.validate_platform_integrity()")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
