#!/usr/bin/env python3
"""Scaffold a new lab_communicator backend + optional lab_view bundle for cloud-labs.

Use this when building a **digital twin**, bench simulator, or any lab that should
speak the same HTTP + JSON protocol as cloud-labs (without forking ``main.py``).

Quick start (from repository root)::

  python scripts/create_lab_communicator.py bench_twin --with-lab-view
  # .env → LAB_VIEW_PATH=backend/lab_communicator/bench_twin/lab_view
  # Edit lab_view/active_catalog.json + component_library.json for your parts
  # Implement backend/lab_communicator/bench_twin/primitives.py

What cloud-labs needs from you (see generated INTEGRATORS.md for the full checklist):

  1. **lab_view bundle** — mandatory JSON files (layout, catalog, manifest, …)
  2. **lab_manifest.json** — ``"communicator": "<your_id>"`` selects your class
  3. **Register backend** — script appends to ``lab_communicator/extra_communicators.py``
  4. **LabCommunicator subclass** — ``communicator.py`` hooks + ``primitives.py`` hardware
  5. **Catalog** — ``component_library.json`` declares capabilities per ``tag_id``

Architecture references:

  - ``backend/lab_communicator/README.md`` — adapter layout + bootstrap rules
  - ``backend/lab_model/ARCHITECTURE.md`` — primitives, tunables, telemetry
  - ``capability_contract.md`` / ``CLOUDLAB_CONTRACT.md`` — catalog ↔ hardware contract

Rules:

  - Package name must be ``snake_case`` (letters, digits, underscore; cannot start with a digit).
  - Names ``mock``, ``real``, ``shared``, ``tests`` are reserved.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import sys
from datetime import datetime
from pathlib import Path


_RESERVED = frozenset({"mock", "real", "shared", "tests"})
_NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _snake_to_class(name: str) -> str:
    parts = [p for p in name.split("_") if p]
    return "".join(p[:1].upper() + p[1:] for p in parts)


def _minimal_lab_state() -> dict:
    return {
        "system_status": "IDLE",
        "last_updated": datetime.now().isoformat(),
        "components": {},
        "optimization_step": 0,
        "optimization_run_dir": None,
        "holding": {
            "tag_id": None,
            "nominal_pose": None,
            "requires_operator_confirm": False,
        },
    }


def _write_init(pkg: Path, module: str, class_name: str) -> None:
    text = f'''"""Placeholder lab communicator backend (scaffold).

Import::

    from lab_communicator.{module} import {class_name}

Generated by ``scripts/create_lab_communicator.py`` — replace stub primitives
with real hardware or simulation logic.
"""

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from lab_communicator.{module}.communicator import {class_name}

__all__ = ["{class_name}"]


def __getattr__(name: str):
    if name == "{class_name}":
        from lab_communicator.{module}.communicator import {class_name}
        return {class_name}
    raise AttributeError(f"module 'lab_communicator.{module}' has no attribute {{name!r}}")
'''
    (pkg / "__init__.py").write_text(text, encoding="utf-8")


def _write_communicator(pkg: Path, module: str, class_name: str) -> None:
    text = f'''"""{class_name} — checklist-shaped placeholder (see lab_communicator/README.md)."""

from __future__ import annotations

import json
import os
from typing import Any, Callable, Dict, Optional, Tuple

from lab_communicator.base import LabCommunicator
from lab_model.catalog.bundle import merged_catalog_maps
from lab_communicator.shared.lab_view_config import get_lab_view_paths
from lab_model.state.snapshot import LabPose


class {class_name}(LabCommunicator):
    """Memory-resident lab backend with stub primitives (asyncio sleep / no-op returns).

    Replace :mod:`lab_communicator.{module}.primitives` with real hardware steps.
    """

    log_prefix = "[{module.upper()} LAB]"

    def __init__(self) -> None:
        super().__init__()
        paths = get_lab_view_paths()
        print(f"{{self.log_prefix}} LAB_VIEW_PATH={{paths.root_dir}}")

        rows, cmap = merged_catalog_maps()
        self.catalog = rows
        self.catalog_map = cmap

        if os.path.isfile(paths.lab_state_json):
            with open(paths.lab_state_json, "r", encoding="utf-8") as f:
                self.current_state = json.load(f)
        # else: keep seeded defaults from :meth:`LabCommunicator.__init__`

        # Optional table-cam lifecycle (live feed / preview). Copy mock/communicator.py for full synthetic MJPEG.
        self._table_cam_connected: Dict[int, bool] = {{1: False, 2: False}}
        self._table_cam_streaming: Dict[int, bool] = {{1: False, 2: False}}

    def _persist_state(self) -> None:
        pass

    def refresh_state(self) -> None:
        self.refresh_pose_from_camera()

    async def _primitive_prepare_teleop(self, target_id: str) -> Tuple[bool, str]:  # noqa: ARG002
        """Return (True, \"ok\") when your twin is ready for TeleOp; override for real setup."""
        return True, "ok"

    def table_cam_connect(self, cam_id: int) -> Tuple[bool, str]:
        if int(cam_id) not in (1, 2):
            return False, "cam_id must be 1 or 2"
        self._table_cam_connected[int(cam_id)] = True
        return True, "ok"

    def table_cam_live_set(
        self, cam_id: int, enabled: bool, *, profile: str = "default"  # noqa: ARG002
    ) -> Tuple[bool, str]:
        if int(cam_id) not in (1, 2):
            return False, "cam_id must be 1 or 2"
        if enabled and not self._table_cam_connected.get(int(cam_id)):
            return False, "connect camera first"
        self._table_cam_streaming[int(cam_id)] = bool(enabled)
        return True, "ok"

    def get_table_cam_stream(self, cam_id: int = 1, fps: int = 18):  # noqa: ARG002
        raise NotImplementedError(
            "Implement get_table_cam_stream for live MJPEG, or copy from lab_communicator/mock/communicator.py"
        )

    def get_video_stream(self, fps: int = 10):  # noqa: ARG002
        while True:
            yield b""
            break

    # --- Primitive hooks (1-line delegations) ---

    async def _primitive_move_motor(self, target_id: str, motor_id: int, distance: float) -> None:
        from lab_communicator.{module}.primitives import primitive_move_motor
        await primitive_move_motor(self, target_id, motor_id, distance)

    async def _primitive_move_component(self, target_id: str, commanded: LabPose):
        from lab_communicator.{module}.primitives import primitive_move_component
        return await primitive_move_component(self, target_id, commanded)

    async def _primitive_pick_component(
        self, target_id: str, commanded: LabPose, params: Dict[str, Any]
    ) -> float:
        from lab_communicator.{module}.primitives import primitive_pick_component
        return await primitive_pick_component(self, target_id, commanded, params)

    async def _primitive_hover_component(
        self, target_id: str, commanded: LabPose, speed: int
    ) -> Optional[LabPose]:
        from lab_communicator.{module}.primitives import primitive_hover_component
        return await primitive_hover_component(self, target_id, commanded, speed)

    async def _primitive_place_from_hover(
        self, target_id: str, commanded: LabPose, params: Dict[str, Any]
    ) -> None:
        from lab_communicator.{module}.primitives import primitive_place_from_hover
        await primitive_place_from_hover(self, target_id, commanded, params)

    async def _primitive_scan_rotate_in_place(
        self,
        *,
        target_id: str,
        mode: str,
        theta_min: float,
        theta_max: float,
        speed: float,
        axis: str,
        base_x: float,
        base_y: float,
        base_z: Optional[float],
        params: Dict[str, Any],
        on_rotation_update: Callable[[float], None],
    ) -> None:
        from lab_communicator.{module}.primitives import primitive_scan_rotate_in_place
        await primitive_scan_rotate_in_place(
            self,
            target_id=target_id,
            mode=mode,
            theta_min=theta_min,
            theta_max=theta_max,
            speed=speed,
            axis=axis,
            base_x=base_x,
            base_y=base_y,
            base_z=base_z,
            params=params,
            on_rotation_update=on_rotation_update,
        )

    async def _primitive_record_measurables(self, tag_id: str, catalog_meta: Dict[str, Any]):
        from lab_communicator.{module}.primitives import primitive_record_measurables
        return await primitive_record_measurables(self, tag_id, catalog_meta)

    async def _primitive_optimize_component(
        self,
        *,
        target_id: str,
        strategy_name: str,
        params: Dict[str, Any],
        live_pose_callback: Callable[..., None],
    ):
        from lab_communicator.{module}.primitives import primitive_optimize_component
        return await primitive_optimize_component(
            self,
            target_id=target_id,
            strategy_name=strategy_name,
            params=params,
            live_pose_callback=live_pose_callback,
        )

    async def _primitive_add_component_to_state(
        self, component_data: Dict[str, Any], existing_components: Dict[str, Any]
    ):
        from lab_communicator.{module}.primitives import primitive_add_component_to_state
        return await primitive_add_component_to_state(self, component_data, existing_components)
'''
    (pkg / "communicator.py").write_text(text, encoding="utf-8")


def _write_primitives(pkg: Path, module: str, class_name: str) -> None:
    text = f'''"""Stub primitive implementations for :class:`~lab_communicator.{module}.communicator.{class_name}`.

Replace sleeps with real hardware / simulation. Do not read or write
``communicator.current_state`` here — the base orchestrator owns state
(see ``lab_model.platform`` integrity checks and ``lab_communicator/README.md``).
"""

from __future__ import annotations

import asyncio
import random
from typing import TYPE_CHECKING, Any, Callable, Dict, Optional

from lab_model.domain.component import PRESENCE_BREADBOARD, new_component_entry
from lab_model.domain.holding import DEFAULT_HOVER_Z_MM

from lab_model.state.snapshot import LabPose

if TYPE_CHECKING:
    from lab_communicator.{module}.communicator import {class_name}


async def primitive_move_motor(
    communicator: "{class_name}",  # noqa: ARG001
    target_id: str,  # noqa: ARG001
    motor_id: int,  # noqa: ARG001
    distance: float,  # noqa: ARG001
) -> None:
    await asyncio.sleep(0.05)


async def primitive_pick_component(
    communicator: "{class_name}",  # noqa: ARG001
    target_id: str,  # noqa: ARG001
    commanded: LabPose,  # noqa: ARG001
    params: Dict[str, Any],  # noqa: ARG001
) -> float:
    await asyncio.sleep(0.05)
    return float(DEFAULT_HOVER_Z_MM)


async def primitive_hover_component(
    communicator: "{class_name}",  # noqa: ARG001
    target_id: str,  # noqa: ARG001
    commanded: LabPose,
    speed: int,  # noqa: ARG001
) -> Optional[LabPose]:
    await asyncio.sleep(0.05)
    return LabPose(
        x=commanded.x + random.uniform(-0.03, 0.03),
        y=commanded.y + random.uniform(-0.03, 0.03),
        z=commanded.z,
        rotation=commanded.rotation,
    )


async def primitive_place_from_hover(
    communicator: "{class_name}",  # noqa: ARG001
    target_id: str,  # noqa: ARG001
    commanded: LabPose,  # noqa: ARG001
    params: Dict[str, Any],  # noqa: ARG001
) -> None:
    await asyncio.sleep(0.05)


async def primitive_scan_rotate_in_place(
    communicator: "{class_name}",  # noqa: ARG001
    *,
    target_id: str,  # noqa: ARG001
    mode: str,  # noqa: ARG001
    theta_min: float,
    theta_max: float,
    speed: float,
    axis: str,  # noqa: ARG001
    base_x: float,  # noqa: ARG001
    base_y: float,  # noqa: ARG001
    base_z: Optional[float],  # noqa: ARG001
    params: Dict[str, Any],  # noqa: ARG001
    on_rotation_update: Callable[[float], None],
) -> None:
    steps = max(1, min(12, int(abs(theta_max - theta_min) / max(speed, 1e-6)) + 1))
    for i in range(1, steps):
        frac = i / steps
        cur_rot = theta_min + (theta_max - theta_min) * frac
        on_rotation_update(cur_rot)
        await asyncio.sleep(0.03)


async def primitive_move_component(
    communicator: "{class_name}",  # noqa: ARG001
    target_id: str,  # noqa: ARG001
    commanded: LabPose,
) -> Optional[LabPose]:
    await asyncio.sleep(0.05)
    return LabPose(
        x=commanded.x + random.uniform(-0.05, 0.05),
        y=commanded.y + random.uniform(-0.05, 0.05),
        z=commanded.z,
        rotation=commanded.rotation,
    )


async def primitive_record_measurables(
    communicator: "{class_name}",  # noqa: ARG001
    tag_id: str,  # noqa: ARG001
    catalog_meta: Dict[str, Any],  # noqa: ARG001
):
    await asyncio.sleep(0.02)
    return None


async def primitive_optimize_component(
    communicator: "{class_name}",
    *,
    target_id: str,
    strategy_name: str,  # noqa: ARG001
    params: Dict[str, Any],  # noqa: ARG001
    live_pose_callback: Callable[..., None],
):
    tun = communicator.return_tunables_for_tag(target_id)
    np = tun.get("nominal_pose") or {{}}
    base_x = float(np.get("x", 0.0))
    base_y = float(np.get("y", 0.0))
    base_rot = float(np.get("rotation", 0.0))
    for k in range(1, 4):
        await asyncio.sleep(0.05)
        frac = k / 3.0
        live_pose_callback(pose={{"x": base_x, "y": base_y, "rotation": base_rot + frac}})
    return {{
        "score": 0.5,
        "final_pose": {{"x": base_x, "y": base_y, "rotation": base_rot + 1.0}},
    }}


async def primitive_add_component_to_state(
    communicator: "{class_name}",  # noqa: ARG001
    component_data: Dict[str, Any],
    existing_components: Dict[str, Any],  # noqa: ARG001
):
    tag_id = component_data.get("tag_id")
    comp_type = component_data.get("type", "OPTICAL_MIRROR")
    await asyncio.sleep(0.02)
    return new_component_entry(
        tag_id,
        comp_type,
        presence=PRESENCE_BREADBOARD,
        nominal_pose={{"x": 0.0, "y": 0.0, "rotation": 0.0}},
        meas_pose={{"x": 0.0, "y": 0.0, "rotation": 0.0}},
        placement_mode="MANUAL",
        in_storage=False,
        slot=None,
    )


__all__ = [
    "primitive_move_motor",
    "primitive_pick_component",
    "primitive_hover_component",
    "primitive_place_from_hover",
    "primitive_scan_rotate_in_place",
    "primitive_move_component",
    "primitive_record_measurables",
    "primitive_optimize_component",
    "primitive_add_component_to_state",
]
'''
    (pkg / "primitives.py").write_text(text, encoding="utf-8")


def _copy_lab_view(template: Path, dest: Path, *, communicator_id: str) -> None:
    if dest.exists():
        raise SystemExit(f"lab_view destination already exists: {dest}")
    shutil.copytree(template, dest)
    lab_state_path = dest / "lab_state.json"
    if not lab_state_path.is_file():
        with open(lab_state_path, "w", encoding="utf-8") as f:
            json.dump(_minimal_lab_state(), f, indent=2)
            f.write("\n")
    manifest_path = dest / "lab_manifest.json"
    manifest: dict = {
        "version": 1,
        "description": "Deployment identity for this lab view bundle.",
        "communicator": communicator_id,
        "session_checkpoint": True,
    }
    if communicator_id == "real":
        manifest["lab_automation_path"] = "../lab_automation"
    with open(manifest_path, "w", encoding="utf-8") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")


        json.dump(manifest, f, indent=2)
        f.write("\n")


def _write_integrators_md(pkg: Path, module: str, class_name: str, *, lab_view_rel: str) -> None:
    text = f"""# Integrating `{module}` with cloud-labs

Generated by ``scripts/create_lab_communicator.py``. Give this file to anyone wiring a
digital twin or external lab stack to the cloud-labs UI.

## 1. Environment (one line)

```env
LAB_VIEW_PATH={lab_view_rel}
```

Do **not** set ``LAB_MODE`` manually — it is derived from ``lab_manifest.json`` → ``communicator``.

## 2. lab_view bundle (you must provide or edit)

| File | Required | Your action |
|------|----------|-------------|
| ``lab_manifest.json`` | yes | ``"communicator": "{module}"`` (set by scaffold when using ``--with-lab-view``) |
| ``layout.json`` | yes | Bench bounds, storage grid, danger zone |
| ``component_library.json`` | yes | Full catalog: ``capabilities`` per ``tag_id`` (tunables, measurables, telemetry, primitives) |
| ``active_catalog.json`` | yes | ``{{"tag_ids": [...]}}`` — which tags appear in the UI / boot scan |
| ``laser_lines.json`` | yes | Laser overlay geometry (can be empty array) |
| ``motor_rotations.json`` | yes | Motor angle cache (can start ``{{}}``) |
| ``table_cam_preview.json`` | yes | JPEG tuning for table cams (copy from mock/real template) |
| ``lab_state.json`` | recommended | Initial ``components`` + ``holding`` snapshot |
| ``recipes/``, ``states/``, ``camera_captures/`` | auto-created | Created at bootstrap if missing |

Validate catalog shape with cloud-labs boot (``validate_catalog_v1`` runs automatically).

## 3. Backend code (replace stubs)

| File | Purpose |
|------|---------|
| ``communicator.py`` | Subclass ``LabCommunicator`` — init, persistence, delegate ``_primitive_*`` |
| ``primitives.py`` | **State-free** hardware/simulation steps (never touch ``communicator.current_state``) |

### Primitive hooks to implement first (minimum viable twin)

| Primitive | Stub function | Notes |
|-----------|---------------|-------|
| ``MOVE_COMPONENT`` | ``primitive_move_component`` | Table reposition |
| ``PICK_COMPONENT`` / ``HOVER`` / ``PLACE_FROM_HOVER`` | pick/hover/place stubs | In-air workflow |
| ``RECORD_MEASURABLES`` | ``primitive_record_measurables`` | Camera / sensor readback |
| ``SCAN`` (inventory) | via ``refresh_pose_from_camera`` or real scan hook | See mock/real |

Inherited from ``base.LabCommunicator`` (override only if needed):

| Feature | Override on class |
|---------|-------------------|
| TeleOp | ``_primitive_prepare_teleop``, ``read_pose``, ``set_target`` (see ``real/teleop_bridge``) |
| Live feed | ``table_cam_connect``, ``table_cam_live_set``, ``get_table_cam_stream`` — copy from ``mock/communicator.py`` for synthetic MJPEG |
| Optimization | ``primitive_optimize_component`` |

Full handler audit: ``python -c "from lab_model.platform import audit_primitive_handlers; from lab_communicator.{module}.communicator import {class_name}; print(audit_primitive_handlers({class_name}))"``

## 4. Registration

Your backend is registered in ``lab_communicator/extra_communicators.py``:

```python
register_communicator("{module}", {class_name})
```

``shared/communicator_factory.py`` loads that module at import time.

## 5. Catalog ↔ your software

For each ``tag_id`` in ``component_library.json``:

- **``capabilities.primitives``** — which buttons appear in the UI; cloud-labs refuses undeclared primitives.
- **``capabilities.statecontrol.tunables``** — intent fields (pose, exposure, motor setpoints); your twin should accept writes that match min/max.
- **``capabilities.telemetry.live_feed.stream``** — URL for MJPEG/JPEG poll (usually ``/api/components/{{tag_id}}/telemetry/stream``).
- **``properties.hardware_binding``** (optional) — maps catalog row to your driver (``recorder_tcp``, ``opencv_usb``, …).

Cloud-labs owns HTTP routes; your communicator implements the methods those routes call.

## 6. Run & test

```bash
python backend/main.py
# open frontend — LAB_VIEW_PATH bundle drives catalog + communicator
```

Compare behavior to ``mock`` first (same protocol, simulated physics).

## 7. Further reading

- ``backend/lab_communicator/README.md``
- ``backend/lab_model/primitives/README.md``
- ``capability_contract.md``
"""
    (pkg / "INTEGRATORS.md").write_text(text, encoding="utf-8")


def _register_communicator(module: str, class_name: str, root: Path) -> None:
    extra_path = root / "backend" / "lab_communicator" / "extra_communicators.py"
    block = (
        f"\nfrom lab_communicator.{module} import {class_name}\n"
        f"from lab_communicator.shared.communicator_factory import register_communicator\n"
        f'register_communicator("{module}", {class_name})\n'
    )
    existing = extra_path.read_text(encoding="utf-8") if extra_path.is_file() else ""
    if f'register_communicator("{module}"' in existing:
        return
    with open(extra_path, "a", encoding="utf-8") as f:
        if existing and not existing.endswith("\n"):
            f.write("\n")
        f.write(block)


def main() -> int:
    parser = argparse.ArgumentParser(description="Create a lab_communicator backend scaffold.")
    parser.add_argument(
        "name",
        help="Python package name (snake_case), e.g. bench_sim -> BenchSimLabCommunicator",
    )
    parser.add_argument(
        "--with-lab-view",
        action="store_true",
        help="Copy lab_view starter files from real/lab_view/default into --lab-view-root.",
    )
    parser.add_argument(
        "--lab-view-root",
        type=str,
        default="",
        help="Destination directory for the bundle (default: backend/lab_communicator/<name>/lab_view).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Allow overwriting an existing communicator package directory.",
    )
    parser.add_argument(
        "--no-register",
        action="store_true",
        help="Do not append register_communicator() to lab_communicator/extra_communicators.py.",
    )
    args = parser.parse_args()

    name = args.name.strip().lower().replace("-", "_")
    if not _NAME_RE.match(name):
        print("Invalid name: use snake_case [a-z][a-z0-9_]*", file=sys.stderr)
        return 2
    if name in _RESERVED:
        print(f"Reserved package name: {name}", file=sys.stderr)
        return 2

    root = _repo_root()
    lc_root = root / "backend" / "lab_communicator"
    pkg = lc_root / name
    if pkg.exists() and not args.force:
        print(f"Already exists (use --force): {pkg}", file=sys.stderr)
        return 2

    class_name = _snake_to_class(name) + "LabCommunicator"

    if pkg.exists():
        shutil.rmtree(pkg)
    pkg.mkdir(parents=True)

    _write_init(pkg, name, class_name)
    _write_communicator(pkg, name, class_name)
    _write_primitives(pkg, name, class_name)

    lv_template = lc_root / "real" / "lab_view" / "default"
    if not lv_template.is_dir():
        print(f"Missing template lab_view: {lv_template}", file=sys.stderr)
        return 2

    lab_view_dest: Path | None = None
    lab_view_rel = ""
    if args.with_lab_view:
        lab_view_dest = Path(args.lab_view_root) if args.lab_view_root else pkg / "lab_view"
        if not lab_view_dest.is_absolute():
            lab_view_dest = root / lab_view_dest
        _copy_lab_view(lv_template, lab_view_dest, communicator_id=name)
        lab_view_rel = lab_view_dest.relative_to(root).as_posix()

    _write_integrators_md(pkg, name, class_name, lab_view_rel=lab_view_rel or f"backend/lab_communicator/{name}/lab_view")

    if not args.no_register:
        _register_communicator(name, class_name, root)

    print(f"Created package: backend/lab_communicator/{name}/")
    print(f"  Class: {class_name}")
    print(f"  Guide: backend/lab_communicator/{name}/INTEGRATORS.md")
    if lab_view_dest is not None:
        print(f"  lab_view: {lab_view_dest.relative_to(root)}")
        print()
        print("Next steps:")
        print(f"  1. .env -> LAB_VIEW_PATH={lab_view_rel}")
        print(f'  2. lab_manifest.json -> "communicator": "{name}"')
        print(f"  3. Edit active_catalog.json + component_library.json for your bench")
        print(f"  4. Implement lab_communicator/{name}/primitives.py")
    else:
        print()
        print("Re-run with --with-lab-view to copy a starter lab_view bundle.")
        print("Or point LAB_VIEW_PATH at any bundle with the mandatory files (see INTEGRATORS.md).")
    if args.no_register:
        print()
        print(f"Skipped factory registration — add register_communicator(\"{name}\", {class_name}) to extra_communicators.py")
    else:
        print()
        print(f"Registered in lab_communicator/extra_communicators.py")
    print()
    print("Verify: python -m pytest backend/tests/test_platform_integrity.py -q")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
